USE dbLMS
GO

SELECT BORROWER.Name, BORROWER.[Address], COUNT(BOOK_LOANS.CardNo) AS NumberOfLoans 
FROM BORROWER
INNER JOIN BOOK_LOANS
ON BOOK_LOANS.CardNo = BORROWER.CardNo
GROUP BY BORROWER.Name, BORROWER.[Address]
HAVING COUNT(BOOK_LOANS.CardNo) > 5



