USE dbLMS
GO

--Sharpstown
SELECT COUNT(*) 
AS Sharpstown
FROM LIBRARY_BRANCH
INNER JOIN BOOK_LOANS 
ON LIBRARY_BRANCH.BranchID = BOOK_LOANS.BranchID
WHERE BranchName = 'Sharpstown'

--Central
SELECT COUNT(*) 
AS Central
FROM LIBRARY_BRANCH
INNER JOIN BOOK_LOANS 
ON LIBRARY_BRANCH.BranchID = BOOK_LOANS.BranchID
WHERE BranchName = 'Central'

--East
SELECT COUNT(*) 
AS East
FROM LIBRARY_BRANCH
INNER JOIN BOOK_LOANS 
ON LIBRARY_BRANCH.BranchID = BOOK_LOANS.BranchID
WHERE BranchName = 'East'

--West
SELECT COUNT(*) 
AS West
FROM LIBRARY_BRANCH
INNER JOIN BOOK_LOANS 
ON LIBRARY_BRANCH.BranchID = BOOK_LOANS.BranchID
WHERE BranchName = 'West'
