USE dbLMS
GO

SELECT BOOK.Title, BOOK_COPIES.No_Of_Copies
FROM BOOK
FULL OUTER JOIN BOOK_COPIES
ON BOOK.BookID = BOOK_COPIES.BookID
FULL OUTER JOIN BOOK_AUTHORS
ON BOOK_COPIES.BookID = BOOK_AUTHORS.BookID
FULL OUTER JOIN LIBRARY_BRANCH
ON BOOK_COPIES.BranchID = LIBRARY_BRANCH.BranchID
WHERE AuthorName = 'Stephen King'  AND BranchName = 'Central' 



